### PR TITLE
Add perameters to keyuri

### PR DESCRIPTION
**Pull request by UziTech**
Adds the `algorithm`, `digits`, and `period` parameters to the keyuri based on the format in https://github.com/google/google-authenticator/wiki/Key-Uri-Format

### TODO:
- [x] Fix tests
- [x] Add new tests
- [x] Add documentation about authenticator apps not accepting all parameters

### CODE REVIEW

**Comment by UziTech** [comment]
I started this PR to fix https://github.com/yeojz/otplib/issues/166#issuecomment-515037694

I know the tests will fail but I wanted to make sure this was the right direction before I invest too much time into it.

**Comment by yeojz** [comment]
@UziTech Thanks. Looks good. 👍

**Comment by UziTech** [comment]
Looks like everything is working.

I added documentation to the readme about Google Authenticator ignoring some options in the QR Code example. I'm not sure if there is any other place we should document that.

**Comment by yeojz** [comment]
merged. Thanks!

**Pull request merged**
